### ISSUE TITLE
Notes 

### ISSUE THREAD

**Issue by JimmyBjorklund** [kodermax/kubectl-aws-eks#13]
Hi, After some tries it now works great, i found two things.
1. If you have profiles remove them from the KUBE_CONFIG_DATA.
2. If you have multiple sections in, you KUBE_CONFIG_DATA remove all but the one you are planning to use.

**Comment by jurampark-pala** [comment]
Having same issue, could you elaborate a little more? I only put 1 cluster, 1 context and 1 user ub kubeconfig file and used it to generate base64 encoding string but still having an issue.

**Comment by jurampark-pala** [comment]
> Hi, After some tries it now works great, i found two things.
> 
> 1. If you have profiles remove them from the KUBE_CONFIG_DATA.
> 2. If you have multiple sections in, you KUBE_CONFIG_DATA remove all but the one you are planning to use.

Having same issue, could you elaborate a little more? I only put 1 cluster, 1 context and 1 user ub kubeconfig file and used it to generate base64 encoding string but still having an issue.
