### ISSUE TITLE
Specifying versions causes issues

### ISSUE THREAD

**Issue by Rambatino** [kodermax/kubectl-aws-eks#23]
Hello, running into a couple of issues. One when specifying versions I get:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/3631109/167029187-bdca7a41-354f-463c-8452-6dcd07c538c1.png">

The other is: 

``` bash
Using kubectl version: Client Version: v1.24.0
Kustomize Version: v4.5.4
Using aws-iam-authenticator version: {"Version":"0.5.7","Commit":"2a9ee95fecab59fab41a0b646a63227d66113434"}
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

I'm gonna guess by the actions that you may be trying to fix one or both of these? But just thought I'd raise it in case I'm going something wrong.

**Comment by raalzate** [comment]
Dude, the problem is solved by adding the following environment variables:

KUBECTL_VERSION: "v1.22.0"
IAM_VERSION: "0.5.6"

**Comment by HarryF514** [comment]
> Dude, the problem is solved by adding the following environment variables:
> 
> KUBECTL_VERSION: "v1.22.0" IAM_VERSION: "0.5.6"

doesn't work for me.

I added like this.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/4098187/167539232-b52a2043-8379-43ce-aaea-7925677b3fcf.png">

**Comment by iranthau** [comment]
> Dude, the problem is solved by adding the following environment variables:
> 
> KUBECTL_VERSION: "v1.22.0" IAM_VERSION: "0.5.6"

Yes. Thanks.

**Comment by pwilczynskiclearcode** [comment]
`export IAM_VERSION=0.5.7` solved the issue for me
