### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by mdasrafkhan** [kodermax/kubectl-aws-eks#5]
I'm getting this error Unauthorized using this action. My kubeconfig works fine locally 
```
 $ KUBECONFIG=~/.kube/config kubectl get svc
````

**Comment by Genysys** [comment]
Any update on this? Getting this error too.  Do you have a work around @mdasrafkhan ?

**Comment by kodermax** [comment]
Have you added base64 kubeconfig content to github secrets?

**Comment by Omobolanle-Arogundade** [comment]
@Genysys, are you able to connect to your kubernetes cluster using your AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY?

**Comment by Omobolanle-Arogundade** [comment]
Perhaps your access keys don't have the required permissions to access the cluster you're trying to connect to

**Comment by gotchipete** [comment]
FWIW, I'm getting this as well (`You must be logged in to the server (Unauthorized)`) and have tried using AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY with full cluster permissions. Can connect fine from anywhere else.

**Comment by jurampark-pala** [comment]
Having same issue, could you elaborate a little more? I only put 1 cluster, 1 context and 1 user ub kubeconfig file and used it to generate base64 encoding string but still having an issue.

**Comment by frankisinfotech** [comment]
> I'm getting this error Unauthorized using this action. My kubeconfig works fine locally
> 
> ```
>  $ KUBECONFIG=~/.kube/config kubectl get svc
> ```

If you are getting the above error, it is because the IAM user who created the cluster is different from the user trying to authenticate with the cluster. Hence, you must authenticate with the user who created the cluster.
What I mean is, the user who created the cluster, is the same user that must be authenticated with using the command below;
#aws configure

**Comment by ghanshyam-onesliq** [comment]
The issue is still there and with all valid configurations.

**Comment by frankisinfotech** [comment]
Hi @ghanshyam-onesliq, you can reach out to me on https://www.linkedin.com/in/legborsi-frank/, and let me see how I may be of help.

Regards
