### ISSUE TITLE
error: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1

### ISSUE THREAD

**Issue by un1xman** [kodermax/kubectl-aws-eks#6]
I was faced with this error morning. Before everything was working
Related code section
```
      - name: Update deployments
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f k8s/dev/application.yml ```

**Comment by Medd1er** [comment]
Greetings! The same issue for me, pipelines stopped working. Can't update deployments/list pods/etc

**Comment by un1xman** [comment]
@Medd1er  yep i think it is about new release

**Comment by abelnieva** [comment]
same error with 1.0.7 version

**Comment by abelnieva** [comment]
workaround:
update kubeconfig the following 
apiVersion: client.authentication.k8s.io/v1beta1

**Comment by Medd1er** [comment]
Worked like a charm! thanks for a tip @abelnieva

**Comment by kodermax** [comment]
I have updated kubeconfig too.

**Comment by un1xman** [comment]
After changes i get "no kind "Config" is registered for version "client.authentication.k8s.io/v1beta1" in scheme "k8s.io/client-go/tools/clientcmd/api/latest/latest.go:50"  this error

**Comment by Medd1er** [comment]
@un1xman if you changed your config in the way @abelnieva mentioned above - just change back to alpha:
apiVersion: client.authentication.k8s.io/v1alpha1.

**Comment by un1xman** [comment]
@Medd1er  same mate ((  actually by default on my config apiVersion: v1. I changed @abelnieva and your suggestion configs but not working

**Comment by Medd1er** [comment]
@un1xman do you change the top-level apiVersion?

`apiVersion: v1 # <- Do not change it
clusters:
- cluster:
    certificate-authority-data: ...
    server: ...
  name: ...
contexts:
- context:
    cluster: ...
    user: ...
  name:...
current-context: ...
kind: Config
preferences: {}
users:
- name: ...
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1 # <- change this
      args:
      - --region
      - us-west-1
      - eks
      - get-token
      - --cluster-name
      - ...
      command: aws
      env:
      - name: AWS_PROFILE
        value: ...`

**Comment by un1xman** [comment]
@Medd1er it was already so ((

**Comment by Medd1er** [comment]
@un1xman can you post your config if possible?

**Comment by abelnieva** [comment]
I had to revert to  client.authentication.k8s.io/v1alpha1 my config today, everything is working again .
