### ISSUE TITLE
When is v1.0.8 published?

### ISSUE THREAD

**Issue by yss14** [kodermax/kubectl-aws-eks#9]
Are there any plans to publish v1.0.8, because in the readme `@master` is used as version, which results in a build of the `kubectl-aws-eks` action everytime my workflow runs (3-5 minutes).

![Screenshot 2021-10-28 at 18 57 21](https://user-images.githubusercontent.com/4346842/139301637-93d799a7-1538-48ff-bbf1-e78216a0c084.png)

**Comment by kodermax** [comment]
Published! Thanks for the notice.
